### ISSUE TITLE
No such property: BxDriverManager for class

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx_kernel_base#10]
try test/ipynb/groovy/slqDriver.ipynb notebook
![image](https://user-images.githubusercontent.com/17744188/86889095-e0df1380-c103-11ea-9182-af93b4eced59.png)

**Comment by jaroslawmalekcodete** [comment]
ready for testing https://github.com/twosigma/beakerx_kernel_base/pull/14
