### ISSUE TITLE
interrupting kernel doesn't work properly

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx_kernel_base#12]
try test/ipynb/groovy/InfiniteLoopGroovyTest.ipynb on classic notebook
run and interrupr kernel will display that kernel have to died
![image](https://user-images.githubusercontent.com/17744188/86892106-7c728300-c108-11ea-8bd1-fe181ca3f1ff.png)

![image](https://user-images.githubusercontent.com/17744188/86892206-9c09ab80-c108-11ea-9865-7e1834f33287.png)

expected result:
![image](https://user-images.githubusercontent.com/17744188/86891686-eb9ba780-c107-11ea-8545-174d18755271.png)

**Comment by jaroslawmalekcodete** [comment]
We need to wait for this beakerx_widgets [PR](https://github.com/twosigma/beakerx_widgets/pull/1).
