### ISSUE TITLE
java.lang.RuntimeException

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx_kernel_base#17]
try on groovy kernel
![image](https://user-images.githubusercontent.com/17744188/88177835-263a2f80-cc32-11ea-99d8-2bfdaa0d1867.png)

**Comment by EfimovVladimir** [comment]
it reproduced again

**Comment by ildipo** [comment]
https://github.com/twosigma/beakerx_kernel_autotranslation/pull/3
