### ISSUE TITLE
beakerx.urlArg bug

### ISSUE THREAD

**Issue by EfimovVladimir** [twosigma/beakerx_kernel_base#9]
try test/ipynb/groovy/accessible_URL_arguments.ipynb?bar=200&foo=300 notebook

When we run cell the kernel hang out

![image](https://user-images.githubusercontent.com/17744188/86468556-4f0c8a80-bd40-11ea-9cae-969d3f386ce9.png)

**Comment by jaroslawmalekcodete** [comment]
We need to wait for this beakerx_widgets [PR](https://github.com/twosigma/beakerx_widgets/pull/1).

**Comment by jaroslawmalekcodete** [comment]
The issue was fixed in https://github.com/twosigma/beakerx_kernel_base/issues/11 in the following PR https://github.com/twosigma/beakerx_kernel_base/pull/16
